version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=olgastash
      - MYSQL_PASSWORD=!QAZcde30
    volumes:
      - ./app_volume:/docker-entrypoint-initdb.d